sudo: required
language: generic
services: docker
script:
- echo $TRAVIS_TAG
- echo $TRAVIS_BUILD_DIR
- sed -i "s/VERSIONTAG/$TRAVIS_TAG/g" preamble_common.in
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src,type=bind kennethkaijieng/latex-tectonic:latest /bin/sh -c "tectonic CookingRecipes.tex"
deploy:
  provider: releases
  api_key:
    secure: S4IqJq65N4DngMRHDUAqBrC8FquLMXuPgkpJSY+J5DVyDRcU34MofECpwOzAXEaKaMdfyrMqINY4ifMt55osPdoQbK5qtbo/cvR1P02Xh3Z+ha/0A80EncLxxgsAW/ARpScovoypV490R4XAxNuMmgET8KNdu6ew76L2r83bGVY6XfMV7KSFSrCNuH/knnnYkjL6OdLRed+kuwDR0eV0nCS1WonoPQvwQIWc5rcPahA29QH1DzDJmruE+VMoWgnCB48qmsVBw+9KTDrFfDnGt9bfVZUyBzRjjg94o1LaJhCzCfwbSpSi3HDByyrGMIFFsMU6qM4hD3siAgVRnXnwv3uQcFofmm9VA+p2TKaHzZfDvKEAvhw5dyRdip207B6Z29CTfwgp2H2CohB7LzFWTnu7g+vrxAH8EIbAYv9Q3+LV6UZoRGIT+cQ4JaRaFrKKXa017k1UfsiSTjVZJkIIwWYAMSp2+WiqnqIIPw+5eo0roq8LYpBhyyP/o4ejE6FKesQ7HgeBalMp5D0CbJlLPOJHYxRhbTapt4ChnDDm0U1Rwm4sD8qqK6pm2wVJD8HXfHThIj9x5p6GqAlCUKTahgafwPX/1vedJ6uKfEU0vUV+qWZ2dBLK2Tm3TSyS/9ozU/Os+sFdqZsifMZwubxGJ8qae24mJRD1kPI84R7lQ3Q=
  file:
  - "$TRAVIS_BUILD_DIR/CookingRecipes.pdf"
  skip_cleanup: true
  on:
    tags: true
    branch: master
